---
- name: Install as default interpreter
  command: make install
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_make_default
  become: yes

- name: Install as alternative interpreter
  command: make altinstall
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: not pyfsrc_make_default
  become: yes
  become_user: "{{ pyfsrc_user }}"

- name: "Create profile exporting PATH"
  lineinfile:
    create: yes
    line: "export PATH"
    path: "$HOME/.bash_profile"
    insertafter: EOF
    state: present
  when: not pyfsrc_make_default
  become: yes
  become_user: "{{ pyfsrc_user }}"

- name: "Add path to user's environment"
  lineinfile:
    state: present
    line: "PATH=$PATH:{{ pyfsrc_install_path }}/bin"
    path: "$HOME/.bash_profile"
    insertbefore: "export PATH"
  when: not pyfsrc_make_default
  become: yes
  become_user: "{{ pyfsrc_user }}"

- name: Clean up build folder and archive
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pyfsrc_src_pkg_path }}"
    - "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_cleanup_downloads
