---
- name: Install as default interpreter
  command: make install
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_make_default
  become: yes

- name: Install as alternative interpreter
  command: make altinstall
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: not pyfsrc_make_default
  become: yes
  become_user: "{{ pyfsrc_user }}"

- name: Clean up build folder and archive
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pyfsrc_src_pkg_path }}"
    - "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_cleanup_downloads
