---

- include: "setup-{{ ansible_os_family }}.yml"
  static: no

- name: Download the tar ball
  get_url: url="{{ pyfsrc_download_url }}" dest="{{ pyfsrc_src_pkg_path }}"

- name: Untar the source package
  unarchive:
    src: "{{ pyfsrc_src_pkg_path }}"
    dest: "{{ pyfsrc_download_dir }}"
    creates: "{{ pyfsrc_src_dir_path }}"
    copy: no

- name: Run configure
  command: "./configure --prefix={{ pyfsrc_install_path }}"
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Run make
  command: make
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Run make install
  command: make install
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_make_default
  become: yes

- name: Run make altinstall
  command: make altinstall
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: not pyfsrc_make_default
  become: yes
  become_user: "{{ pyfsrc_user }}"

- name: Clean up the source files
  command: rm -r "{{ item }}"
  with_items:
    - "{{ pyfsrc_src_pkg_path }}"
    - "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_cleanup_downloads
