---
# tasks file for python-from-src

- set_fact:
    pyfsrc_exec: "python{{ pyfsrc_version|regex_replace('(\\d\\.\\d+)\\..*$', '\\1') }}"

- name: Determine if this Python version already installed
  shell: "[ $({{ pyfsrc_exec|quote }} -V 2>&1 | sed 's/Python //g') = {{ pyfsrc_version|quote }} ]"
  register: is_installed
  ignore_errors: yes
  changed_when: no

- name: Setup compilation
  include_tasks: setup.yml
  when: pyfsrc_force_install or is_installed|failed

- name: Compile source
  command: make
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_force_install or is_installed|failed

- name: Install python
  include_tasks: install.yml
  when: pyfsrc_force_install or is_installed|failed
