---
# tasks file for python-from-src

- set_fact:
    pyfsrc_exec: "python{{ pyfsrc_version|regex_replace('(\\d+\\.\\d+)\\..*$', '\\\\1') }}"

- name: check if python version installed
  command: "command -v {{ pyfsrc_exec }}"
  register: is_installed
  ignore_errors: yes

- include_tasks: install.yml
  when: pyfsrc_force_install or is_installed|failed
