---
# tasks file for python-from-src

- name: "Determine Python executable's name"
  set_fact:
    pyfsrc_exec:    "python{{ pyfsrc_version|regex_replace('(\\d\\.\\d+)\\..*$', '\\1') }}"

- name: Determine if {{ pyfsrc_exec }} is up-to-date
  shell: >
    [ "$({{ pyfsrc_install_path|quote }}/bin/{{ pyfsrc_exec|quote }} -V 2>&1 | sed 's/Python //g')" == {{ pyfsrc_version|quote }} ]
  register: is_installed
  ignore_errors: yes
  changed_when: no

- name: Installing requested Python version
  include_tasks: new_version.yml
  when: pyfsrc_force_install or is_installed|failed

- name: install python basic tools
  command: "{{ pyfsrc_install_path|quote }}/bin/{{ pyfsrc_exec|quote }} -m pip install {{ item }}"
  with_items:
    - "virtualenv"
    - "wheel"
  register: package_install
  changed_when: "package_install.stdout|search('Successfully installed')"
