---
- name: Setup source for compilation
  include_tasks: setup.yml

- name: Install python with shared libraries
  include_tasks: shared.yml

- name: Install static python binary
  include_tasks: static.yml

- name: Post-install tweaks
  include_tasks: postinstall.yml

