---
- name: "Create profile exporting PATH"
  lineinfile:
    create: yes
    line: "export PATH"
    path: "$HOME/.bash_profile"
    insertafter: EOF
    state: present

- name: "Add path to user's environment"
  lineinfile:
    state: present
    line: "PATH=$PATH:{{ pyfsrc_install_path }}/bin"
    path: "$HOME/.bash_profile"
    insertbefore: "export PATH"

- name: Clean up build folder and archive
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pyfsrc_src_pkg_path }}"
    - "{{ pyfsrc_src_dir_path }}"
  when: pyfsrc_cleanup_downloads
