---
- name: Download source
  get_url:
    url: "{{ pyfsrc_download_url }}"
    dest: "{{ pyfsrc_src_pkg_path }}"

- name: Unarchive source
  unarchive:
    src: "{{ pyfsrc_src_pkg_path }}"
    dest: "{{ pyfsrc_download_dir }}"
    creates: "{{ pyfsrc_src_dir_path }}"

