---
- name: Download source
  get_url:
    url: "{{ pyfsrc_download_url }}"
    dest: "{{ pyfsrc_src_pkg_path }}"

- name: Extract source
  unarchive:
    src: "{{ pyfsrc_src_pkg_path }}"
    dest: "{{ pyfsrc_download_dir }}"
    remote_src: yes

