---
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Download source
  get_url: url="{{ pyfsrc_download_url }}" dest="{{ pyfsrc_src_pkg_path }}"

- name: Unarchive source
  unarchive:
    src: "{{ pyfsrc_src_pkg_path }}"
    dest: "{{ pyfsrc_download_dir }}"
    creates: "{{ pyfsrc_src_dir_path }}"
    copy: no

- name: Configure package
  command: "./configure --prefix={{ pyfsrc_install_path }}"
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Cleanup for build
  command: make clean
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
