---
- name: Configure
  command: "./configure --enable-shared --enable-unicode=ucs4 --prefix={{ pyfsrc_install_path }}"
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Cleanup for build
  command: make clean
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Compile
  command: make
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"


- name: Install to {{ pyfsrc_install_path }}
- name: Install shared libraries
  command: make install
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
