---
- name: Configure
  command: "./configure --prefix={{ pyfsrc_install_path }}"
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Cleanup for build
  command: make clean
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Compile
  command: make
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"

- name: Install shared libraries to {{ pyfsrc_install_path }}
  command: make install
  args:
    chdir: "{{ pyfsrc_src_dir_path }}"
